// Static PHP language data - exported separately to avoid loading everything into memory at once
module.exports = {
  phpKeywords: [
    'abstract', 'and', 'array', 'as', 'break', 'callable', 'case', 'catch',
    'class', 'clone', 'const', 'continue', 'declare', 'default', 'die', 'do',
    'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor', 'endforeach',
    'endif', 'endswitch', 'endwhile', 'eval', 'exit', 'extends', 'final',
    'finally', 'fn', 'for', 'foreach', 'function', 'global', 'goto', 'if',
    'implements', 'include', 'include_once', 'instanceof', 'insteadof',
    'interface', 'isset', 'list', 'match', 'namespace', 'new', 'or', 'print',
    'private', 'protected', 'public', 'readonly', 'require', 'require_once',
    'return', 'static', 'switch', 'throw', 'trait', 'try', 'unset', 'use',
    'var', 'while', 'xor', 'yield', 'enum'
  ],

  phpFunctions: {
    'Array Functions': ['array_change_key_case', 'array_chunk', 'array_column', 'array_combine', 'array_count_values', 'array_diff', 'array_diff_assoc', 'array_diff_key', 'array_diff_uassoc', 'array_diff_ukey', 'array_fill', 'array_fill_keys', 'array_filter', 'array_flip', 'array_intersect', 'array_intersect_assoc', 'array_intersect_key', 'array_intersect_uassoc', 'array_intersect_ukey', 'array_key_exists', 'array_key_first', 'array_key_last', 'array_keys', 'array_map', 'array_merge', 'array_merge_recursive', 'array_multisort', 'array_pad', 'array_pop', 'array_product', 'array_push', 'array_rand', 'array_reduce', 'array_replace', 'array_replace_recursive', 'array_reverse', 'array_search', 'array_shift', 'array_slice', 'array_splice', 'array_sum', 'array_udiff', 'array_udiff_assoc', 'array_udiff_uassoc', 'array_uintersect', 'array_uintersect_assoc', 'array_uintersect_uassoc', 'array_unique', 'array_unshift', 'array_values', 'array_walk', 'array_walk_recursive', 'arsort', 'asort', 'compact', 'count', 'current', 'end', 'extract', 'in_array', 'key', 'krsort', 'ksort', 'natcasesort', 'natsort', 'next', 'prev', 'range', 'reset', 'rsort', 'shuffle', 'sizeof', 'sort', 'uasort', 'uksort', 'usort'],
    'String Functions': ['addcslashes', 'addslashes', 'bin2hex', 'chop', 'chr', 'chunk_split', 'convert_uudecode', 'convert_uuencode', 'crc32', 'explode', 'get_html_translation_table', 'hebrev', 'hebrevc', 'hex2bin', 'html_entity_decode', 'htmlentities', 'htmlspecialchars', 'htmlspecialchars_decode', 'implode', 'join', 'lcfirst', 'levenshtein', 'localeconv', 'ltrim', 'md5', 'md5_file', 'metaphone', 'nl2br', 'number_format', 'ord', 'parse_str', 'print', 'printf', 'quoted_printable_decode', 'quoted_printable_encode', 'rtrim', 'sha1', 'sha1_file', 'similar_text', 'soundex', 'sprintf', 'sscanf', 'str_contains', 'str_ends_with', 'str_getcsv', 'str_ireplace', 'str_pad', 'str_repeat', 'str_replace', 'str_rot13', 'str_shuffle', 'str_split', 'str_starts_with', 'str_word_count', 'strcasecmp', 'strchr', 'strcmp', 'strcspn', 'strip_tags', 'stripcslashes', 'stripos', 'stripslashes', 'stristr', 'strlen', 'strnatcasecmp', 'strnatcmp', 'strncasecmp', 'strncmp', 'strpbrk', 'strpos', 'strrchr', 'strrev', 'strripos', 'strrpos', 'strspn', 'strstr', 'strtok', 'strtolower', 'strtoupper', 'strtr', 'substr', 'substr_compare', 'substr_count', 'substr_replace', 'trim', 'ucfirst', 'ucwords', 'wordwrap'],
    'File System': ['basename', 'chgrp', 'chmod', 'chown', 'clearstatcache', 'copy', 'dirname', 'disk_free_space', 'disk_total_space', 'fclose', 'feof', 'fflush', 'fgetc', 'fgetcsv', 'fgets', 'file', 'file_exists', 'file_get_contents', 'file_put_contents', 'fileatime', 'filectime', 'filegroup', 'fileinode', 'filemtime', 'fileowner', 'fileperms', 'filesize', 'filetype', 'flock', 'fnmatch', 'fopen', 'fpassthru', 'fread', 'fseek', 'ftell', 'ftruncate', 'fwrite', 'glob', 'is_dir', 'is_executable', 'is_file', 'is_link', 'is_readable', 'is_uploaded_file', 'is_writable', 'link', 'linkinfo', 'lstat', 'mkdir', 'move_uploaded_file', 'opendir', 'pathinfo', 'pclose', 'popen', 'readfile', 'readdir', 'readlink', 'realpath', 'realpath_cache_get', 'realpath_cache_size', 'rename', 'rewind', 'rewinddir', 'rmdir', 'scandir', 'stat', 'symlink', 'sys_get_temp_dir', 'tempnam', 'tmpfile', 'touch', 'umask', 'unlink'],
    'Date/Time': ['checkdate', 'date', 'date_add', 'date_create', 'date_create_from_format', 'date_default_timezone_get', 'date_default_timezone_set', 'date_diff', 'date_format', 'date_get_last_errors', 'date_parse', 'date_parse_from_format', 'date_sub', 'date_sun_info', 'date_sunrise', 'date_sunset', 'date_timestamp_get', 'date_timestamp_set', 'getdate', 'gettimeofday', 'gmdate', 'gmmktime', 'hrtime', 'idate', 'microtime', 'mktime', 'strftime', 'strtotime', 'time', 'timezone_identifiers_list', 'timezone_location_get', 'timezone_name_get', 'timezone_offset_get', 'timezone_open', 'timezone_transitions_get', 'timezone_version_get'],
    'JSON': ['json_decode', 'json_encode', 'json_last_error', 'json_last_error_msg'],
    'Session': ['session_abort', 'session_cache_expire', 'session_cache_limiter', 'session_commit', 'session_create_id', 'session_decode', 'session_destroy', 'session_encode', 'session_get_cookie_params', 'session_id', 'session_name', 'session_regenerate_id', 'session_reset', 'session_save_path', 'session_set_cookie_params', 'session_set_save_handler', 'session_start', 'session_status', 'session_unset', 'session_write_close'],
    'Database (MySQLi)': ['mysqli_affected_rows', 'mysqli_autocommit', 'mysqli_begin_transaction', 'mysqli_change_user', 'mysqli_close', 'mysqli_commit', 'mysqli_connect', 'mysqli_connect_errno', 'mysqli_connect_error', 'mysqli_data_seek', 'mysqli_dump_debug_info', 'mysqli_errno', 'mysqli_error', 'mysqli_fetch_all', 'mysqli_fetch_array', 'mysqli_fetch_assoc', 'mysqli_fetch_field', 'mysqli_fetch_field_direct', 'mysqli_fetch_fields', 'mysqli_fetch_lengths', 'mysqli_fetch_object', 'mysqli_fetch_row', 'mysqli_field_count', 'mysqli_field_seek', 'mysqli_free_result', 'mysqli_get_client_info', 'mysqli_get_connection_stats', 'mysqli_get_host_info', 'mysqli_get_proto_info', 'mysqli_get_server_info', 'mysqli_info', 'mysqli_init', 'mysqli_insert_id', 'mysqli_more_results', 'mysqli_multi_query', 'mysqli_next_result', 'mysqli_num_fields', 'mysqli_num_rows', 'mysqli_options', 'mysqli_ping', 'mysqli_prepare', 'mysqli_query', 'mysqli_real_escape_string', 'mysqli_real_query', 'mysqli_rollback', 'mysqli_select_db', 'mysqli_set_charset', 'mysqli_sqlstate', 'mysqli_stat', 'mysqli_stmt_affected_rows', 'mysqli_stmt_bind_param', 'mysqli_stmt_bind_result', 'mysqli_stmt_close', 'mysqli_stmt_error', 'mysqli_stmt_errno', 'mysqli_stmt_execute', 'mysqli_stmt_fetch', 'mysqli_stmt_get_result', 'mysqli_stmt_init', 'mysqli_stmt_num_rows', 'mysqli_stmt_result_metadata', 'mysqli_stmt_store_result', 'mysqli_store_result', 'mysqli_thread_id', 'mysqli_use_result', 'mysqli_warning_count'],
    'Password': ['password_algos', 'password_get_info', 'password_hash', 'password_needs_rehash', 'password_verify'],
    'Math': ['abs', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'base_convert', 'bindec', 'ceil', 'cos', 'cosh', 'decbin', 'dechex', 'decoct', 'deg2rad', 'exp', 'expm1', 'floor', 'fmod', 'fdiv', 'hexdec', 'hypot', 'intdiv', 'is_finite', 'is_infinite', 'is_nan', 'lcg_value', 'log', 'log10', 'log1p', 'max', 'min', 'octdec', 'pi', 'pow', 'rad2deg', 'rand', 'random_bytes', 'random_int', 'round', 'sin', 'sinh', 'sqrt', 'tan', 'tanh'],
    'Variable/Type': ['boolval', 'class_alias', 'class_exists', 'class_implements', 'class_parents', 'constant', 'defined', 'doubleval', 'floatval', 'function_exists', 'get_called_class', 'get_class', 'get_class_methods', 'get_class_vars', 'get_declared_classes', 'get_declared_interfaces', 'get_declared_traits', 'get_defined_constants', 'get_defined_functions', 'get_defined_vars', 'get_object_vars', 'get_parent_class', 'get_resource_id', 'get_resource_type', 'gettype', 'intval', 'interface_exists', 'is_array', 'is_bool', 'is_callable', 'is_countable', 'is_double', 'is_float', 'is_int', 'is_integer', 'is_iterable', 'is_long', 'is_null', 'is_numeric', 'is_object', 'is_resource', 'is_scalar', 'is_string', 'method_exists', 'property_exists', 'settype', 'strval', 'trait_exists'],
    'Environment': ['connection_aborted', 'connection_status', 'connection_timeout', 'constant', 'define', 'defined', 'get_cfg_var', 'get_current_user', 'getcwd', 'getenv', 'gethostname', 'getmypid', 'getmyuid', 'getmygid', 'getmyinode', 'getlastmod', 'getopt', 'getrusage', 'ini_get', 'ini_get_all', 'ini_restore', 'ini_set', 'memory_get_peak_usage', 'memory_get_usage', 'php_sapi_name', 'php_uname', 'phpversion', 'putenv', 'set_time_limit', 'sleep', 'sys_getloadavg', 'usleep', 'uniqid'],
    'URL/HTTP': ['base64_decode', 'base64_encode', 'get_headers', 'header', 'header_remove', 'headers_list', 'headers_sent', 'http_build_query', 'parse_url', 'rawurldecode', 'rawurlencode', 'setcookie', 'urldecode', 'urlencode'],
    'cURL': ['curl_close', 'curl_copy_handle', 'curl_errno', 'curl_error', 'curl_escape', 'curl_exec', 'curl_getinfo', 'curl_init', 'curl_multi_add_handle', 'curl_multi_close', 'curl_multi_exec', 'curl_multi_getcontent', 'curl_multi_init', 'curl_multi_remove_handle', 'curl_multi_select', 'curl_pause', 'curl_reset', 'curl_setopt', 'curl_setopt_array', 'curl_share_close', 'curl_share_init', 'curl_share_setopt', 'curl_strerror', 'curl_unescape', 'curl_version'],
    'Hashing/Crypto': ['crypt', 'hash', 'hash_algos', 'hash_copy', 'hash_file', 'hash_final', 'hash_hkdf', 'hash_hmac', 'hash_hmac_file', 'hash_init', 'hash_pbkdf2', 'hash_update', 'hash_update_file', 'hash_update_stream', 'md5', 'md5_file', 'sha1', 'sha1_file'],
    'OpenSSL': ['openssl_cipher_iv_length', 'openssl_decrypt', 'openssl_digest', 'openssl_encrypt', 'openssl_error_string', 'openssl_get_cert_locations', 'openssl_open', 'openssl_pkcs7_decrypt', 'openssl_pkcs7_encrypt', 'openssl_pkcs7_read', 'openssl_pkcs7_sign', 'openssl_pkcs7_verify', 'openssl_pkey_export', 'openssl_pkey_export_to_file', 'openssl_pkey_free', 'openssl_pkey_get_private', 'openssl_pkey_get_public', 'openssl_pkey_new', 'openssl_private_decrypt', 'openssl_private_encrypt', 'openssl_public_decrypt', 'openssl_public_encrypt', 'openssl_random_pseudo_bytes', 'openssl_seal', 'openssl_sign', 'openssl_verify', 'openssl_x509_checkpurpose', 'openssl_x509_fingerprint', 'openssl_x509_free', 'openssl_x509_parse', 'openssl_x509_read'],
    'Multibyte (mbstring)': ['mb_check_encoding', 'mb_chr', 'mb_convert_case', 'mb_convert_encoding', 'mb_convert_kana', 'mb_convert_variables', 'mb_decode_mimeheader', 'mb_decode_numericentity', 'mb_detect_encoding', 'mb_detect_order', 'mb_encode_mimeheader', 'mb_encode_numericentity', 'mb_ereg', 'mb_ereg_match', 'mb_ereg_replace', 'mb_ereg_search', 'mb_ereg_search_getpos', 'mb_ereg_search_getregs', 'mb_ereg_search_init', 'mb_ereg_search_pos', 'mb_ereg_search_regs', 'mb_ereg_search_setpos', 'mb_get_info', 'mb_http_input', 'mb_http_output', 'mb_internal_encoding', 'mb_language', 'mb_list_encodings', 'mb_ord', 'mb_output_handler', 'mb_parse_str', 'mb_regex_encoding', 'mb_send_mail', 'mb_split', 'mb_strcut', 'mb_strimwidth', 'mb_strlen', 'mb_strpos', 'mb_strrpos', 'mb_strtolower', 'mb_strtoupper', 'mb_strwidth', 'mb_substitute_character', 'mb_substr', 'mb_substr_count'],
    'Filter': ['filter_has_var', 'filter_id', 'filter_input', 'filter_input_array', 'filter_list', 'filter_var', 'filter_var_array'],
    'Streams': ['stream_bucket_append', 'stream_bucket_make_writeable', 'stream_bucket_new', 'stream_bucket_prepend', 'stream_context_create', 'stream_context_get_default', 'stream_context_get_options', 'stream_context_get_params', 'stream_context_set_default', 'stream_context_set_option', 'stream_context_set_params', 'stream_copy_to_stream', 'stream_filter_append', 'stream_filter_prepend', 'stream_filter_register', 'stream_get_contents', 'stream_get_filters', 'stream_get_line', 'stream_get_meta_data', 'stream_get_transports', 'stream_get_wrappers', 'stream_is_local', 'stream_notification_callback', 'stream_resolve_include_path', 'stream_select', 'stream_set_blocking', 'stream_set_chunk_size', 'stream_set_read_buffer', 'stream_set_timeout', 'stream_set_write_buffer', 'stream_socket_accept', 'stream_socket_client', 'stream_socket_get_name', 'stream_socket_pair', 'stream_socket_recvfrom', 'stream_socket_sendto', 'stream_socket_server', 'stream_socket_shutdown'],
    'SPL': ['class_uses', 'iterator_apply', 'iterator_count', 'iterator_to_array', 'spl_autoload', 'spl_autoload_call', 'spl_autoload_extensions', 'spl_autoload_functions', 'spl_autoload_register', 'spl_autoload_unregister', 'spl_classes', 'spl_object_hash', 'spl_object_id'],
    'Serialization': ['serialize', 'unserialize'],
    'Tokenizer': ['token_get_all', 'token_name'],
    'Regular Expressions': ['preg_filter', 'preg_grep', 'preg_last_error', 'preg_last_error_msg', 'preg_match', 'preg_match_all', 'preg_quote', 'preg_replace', 'preg_replace_callback', 'preg_replace_callback_array', 'preg_split'],
    'Output Control': ['flush', 'ob_clean', 'ob_end_clean', 'ob_end_flush', 'ob_flush', 'ob_get_clean', 'ob_get_contents', 'ob_get_flush', 'ob_get_length', 'ob_get_level', 'ob_get_status', 'ob_gzhandler', 'ob_implicit_flush', 'ob_list_handlers', 'ob_start', 'output_add_rewrite_var', 'output_reset_rewrite_vars'],
    'Error/Debug': ['assert', 'assert_options', 'debug_backtrace', 'debug_print_backtrace', 'error_clear_last', 'error_get_last', 'error_log', 'error_reporting', 'restore_error_handler', 'restore_exception_handler', 'set_error_handler', 'set_exception_handler', 'trigger_error', 'var_dump', 'var_export', 'print_r']
  },

  phpFunctionCategoryOrder: [
    'Array Functions', 'String Functions', 'Regular Expressions', 'Math',
    'Date/Time', 'File System', 'Streams', 'URL/HTTP', 'JSON', 'Session',
    'Database (MySQLi)', 'Password', 'Hashing/Crypto', 'OpenSSL',
    'Multibyte (mbstring)', 'Filter', 'Serialization', 'Tokenizer', 'SPL',
    'Variable/Type', 'Environment', 'Output Control', 'Error/Debug'
  ],

  phpMagicMethods: [
    '__construct', '__destruct', '__call', '__callStatic', '__get', '__set',
    '__isset', '__unset', '__sleep', '__wakeup', '__serialize', '__unserialize',
    '__toString', '__invoke', '__set_state', '__clone', '__debugInfo'
  ],

  phpConstants: [
    'PHP_VERSION', 'PHP_OS', 'PHP_EOL', 'PHP_INT_MAX', 'PHP_INT_MIN',
    'true', 'false', 'null', 'TRUE', 'FALSE', 'NULL',
    '__LINE__', '__FILE__', '__DIR__', '__FUNCTION__', '__CLASS__',
    '__TRAIT__', '__METHOD__', '__NAMESPACE__'
  ],

  phpSnippets: {
    'class': { prefix: ['class', 'cl', 'cls'], body: ['class ${1:ClassName}', '{', '\tprivate ${2:\\$property};', '', '\tpublic function __construct(${3:\\$param})', '\t{', '\t\t\\$this->${2:property} = ${3:\\$param};', '\t}', '', '\tpublic function ${4:methodName}()', '\t{', '\t\t${5:// method body}', '\t}', '}'], description: 'Create a PHP class (PHP Enhanced Pro)' },
    'function': { prefix: ['function', 'func', 'fn', 'fun'], body: ['function ${1:functionName}(${2:\\$params}): ${3:void}', '{', '\t${4:// function body}', '}'], description: 'Create a PHP function (PHP Enhanced Pro)' },
    'foreach': { prefix: ['foreach', 'fe', 'fore', 'each'], body: ['foreach (${1:\\$array} as ${2:\\$key} => ${3:\\$value}) {', '\t${4:// code}', '}'], description: 'Foreach loop (PHP Enhanced Pro)' },
    'if': { prefix: ['if', 'iff'], body: ['if (${1:condition}) {', '\t${2:// code}', '}'], description: 'If statement (PHP Enhanced Pro)' },
    'ifelse': { prefix: ['ifelse', 'ife', 'ifelsee'], body: ['if (${1:condition}) {', '\t${2:// code}', '} else {', '\t${3:// code}', '}'], description: 'If-else statement (PHP Enhanced Pro)' },
    'switch': { prefix: ['switch', 'sw'], body: ['switch (${1:expression}) {', '\tcase ${2:value}:', '\t\t${3:// code}', '\t\tbreak;', '\tdefault:', '\t\t${4:// code}', '}'], description: 'Switch statement (PHP Enhanced Pro)' },
    'trycatch': { prefix: ['try', 'trycatch', 'tc'], body: ['try {', '\t${1:// code}', '} catch (${2:Exception} ${3:\\$e}) {', '\t${4:// handle exception}', '}'], description: 'Try-catch block (PHP Enhanced Pro)' },
    'prop': { prefix: ['prop', 'property', 'priv'], body: ['private ${1:type} \\$${2:name};'], description: 'Private property (PHP Enhanced Pro)' },
    'pubfn': { prefix: ['pubfn', 'publicfn', 'pubf'], body: ['public function ${1:methodName}(${2:\\$params}): ${3:void}', '{', '\t${4:// code}', '}'], description: 'Public method (PHP Enhanced Pro)' },
    'prifn': { prefix: ['prifn', 'privatefn', 'prif'], body: ['private function ${1:methodName}(${2:\\$params}): ${3:void}', '{', '\t${4:// code}', '}'], description: 'Private method (PHP Enhanced Pro)' },
    'namespace': { prefix: ['namespace', 'ns'], body: ['namespace ${1:Vendor\\\\Package};'], description: 'Namespace declaration (PHP Enhanced Pro)' },
    'use': { prefix: ['use', 'import'], body: ['use ${1:Vendor\\\\Package\\\\ClassName};'], description: 'Use/import statement (PHP Enhanced Pro)' }
  }
};
